# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-02-17 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_socia_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socia',
            name='comentario',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
