# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-02-17 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_auto_20180217_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociasubcategoria',
            name='comentario',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='sociasubcategoria',
            name='referencia',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='sociasubcategoria',
            name='texperiencia',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
