# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-02-25 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_auto_20180224_2357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicidad',
            options={'managed': True, 'verbose_name': 'Publicidad Externa'},
        ),
        migrations.AddField(
            model_name='distrito',
            name='porcentaje_descuento',
            field=models.FloatField(blank=True, max_length=1000, null=True),
        ),
    ]
