# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-03-04 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_auto_20180225_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='distrito',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
