# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-03-04 20:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_categoria_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='portadaphoto',
            name='sexo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Sexo'),
        ),
    ]
