# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-03-08 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_portadaphoto_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='distrito',
            name='latitud',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='distrito',
            name='longitud',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
