# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-03-09 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_auto_20180308_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='sexo',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
