# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-03-21 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_auto_20180321_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='socia',
            name='distancia',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
