# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-03-21 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_socia_distancia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socia',
            name='distancia',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
