# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-03-21 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_serviciosintentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='modelo_celular',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='socia',
            name='modelo_celular',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
