# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-03-23 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_cliente_version_celular'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='notificacion_cuerpo',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='notificacion_titulo',
        ),
        migrations.AddField(
            model_name='serviciosintentos',
            name='detalle',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
