# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-03-23 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_auto_20180323_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciosintentos',
            name='fecha',
            field=models.DateTimeField(blank=True, max_length=1000, null=True),
        ),
    ]
