# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-03-24 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0068_auto_20180323_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Otros',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='servicio',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='tipo_notificacion',
        ),
        migrations.DeleteModel(
            name='Notificacion',
        ),
    ]
