# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-03-25 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0069_auto_20180324_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='socia',
            name='fecha_inscripcion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
