# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-03-25 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0070_socia_fecha_inscripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociasubcategoria',
            name='validar',
            field=models.BooleanField(default=False),
        ),
    ]
