# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-04-08 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0073_auto_20180408_1139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personas',
            options={'managed': True, 'verbose_name': 'Personas'},
        ),
    ]
