# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-04-08 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0074_auto_20180408_1140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personas',
            options={'managed': True, 'verbose_name': 'Persona'},
        ),
        migrations.AddField(
            model_name='personas',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
