# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-04-08 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0076_personas_trabajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='fecha_nacimiento',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='personas',
            name='origen',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
