# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-04-08 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0077_auto_20180408_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='fecha_nacimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
