# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-04-08 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0078_auto_20180408_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='fecha_nacimiento',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
