# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-05-28 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0082_auto_20180527_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracion',
            name='contenido',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
