# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-05-28 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0083_auto_20180527_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='tema',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
