# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-05-28 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0084_configuracion_tema'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='email',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
