# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-05-28 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0085_configuracion_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trafico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=1000, null=True)),
                ('tema', models.CharField(blank=True, max_length=1000, null=True)),
                ('contenido', models.CharField(blank=True, max_length=1000, null=True)),
                ('destino', models.CharField(blank=True, max_length=1000, null=True)),
                ('fecha', models.DateTimeField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Trafico Correo Masivo',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='configuracion',
            options={'managed': True, 'verbose_name': 'Configuracion de Correo Masivo'},
        ),
    ]
