# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-05-28 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0086_auto_20180527_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafico',
            name='fecha',
            field=models.DateField(blank=True, max_length=1000, null=True),
        ),
    ]
