# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-06-12 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0089_servicio_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
