# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-06-12 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0090_servicio_fecha_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serviciopago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pago', models.IntegerField(blank=True, null=True)),
                ('servicio', models.ForeignKey(blank=True, max_length=1000, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Servicio')),
            ],
        ),
    ]
