# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-06-12 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0091_serviciopago'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='pago',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
