# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-06-12 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0092_servicio_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciopago',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
