# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-06-16 22:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0093_serviciopago_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estadocompartir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Estado de Compartir',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='codigo_compartir',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_compartio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socia',
            name='codigo_compartir',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='socia',
            name='fecha_compartio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='duracion_servicio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado_compartir',
            field=models.ForeignKey(blank=True, db_column='estado_compartir', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Estadocompartir'),
        ),
        migrations.AddField(
            model_name='socia',
            name='estado_compartir',
            field=models.ForeignKey(blank=True, db_column='estado_compartir', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Estadocompartir'),
        ),
    ]
