# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-06-17 00:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0095_cliente_fecha_inscripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compartir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_compartir', models.CharField(blank=True, max_length=1000, null=True)),
                ('fecha_compartir', models.DateTimeField(blank=True, null=True)),
                ('socia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='socia', to='app.Socia')),
                ('socia_compartir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='socia_compartir', to='app.Socia')),
            ],
            options={
                'verbose_name': 'Compartir',
                'managed': True,
            },
        ),
    ]
