# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-06-22 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0096_compartir'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategoria',
            name='activar_descuento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='descuento',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
