# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-06-22 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0097_auto_20180621_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategoria',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
