# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-06-22 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0098_subcategoria_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
