# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-06-22 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0099_categoria_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='codigo_recibido',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
