# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-07-08 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0102_configuracion_activa_anuncio'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciopedido',
            name='descuento',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviciopedido',
            name='precio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
