# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-07-08 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0103_auto_20180708_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciopedido',
            name='precio_con_descuento',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
