# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-07-08 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0104_serviciopedido_precio_con_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciopedido',
            name='socia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Socia'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='precio',
            field=models.FloatField(blank=True, null=True, verbose_name='Precio Total'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='referencia',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Direccion'),
        ),
    ]
