# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-07-08 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0105_auto_20180708_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciopedido',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Estado'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Estado'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='referencia',
            field=models.CharField(default='', max_length=1000, verbose_name='Direccion'),
        ),
    ]
