# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-07-09 00:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0106_auto_20180708_1423'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sociadistrito',
            options={'managed': True, 'verbose_name': 'Turno/Socia'},
        ),
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='app.Estado'),
        ),
    ]
