# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-07-09 02:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0107_auto_20180708_1955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sociadistrito',
            options={'managed': True, 'verbose_name': 'Socia/Distrito'},
        ),
    ]
