# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-07-09 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0108_auto_20180708_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='socia',
            name='linea',
            field=models.BooleanField(default=False),
        ),
    ]
