# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-07-24 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0109_socia_linea'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciopedido',
            name='cantidad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
