# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-07-27 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0111_serviciopedido_tipo_vivienda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviciopedido',
            name='tipo_vivienda',
        ),
        migrations.AddField(
            model_name='servicio',
            name='tipo_vivienda',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
