# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-08-03 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0114_promocodigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='precio_promo',
            field=models.FloatField(blank=True, null=True, verbose_name='Precio Promo'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='promo_codigo',
            field=models.ForeignKey(blank=True, max_length=1000, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Promocodigo'),
        ),
    ]
