# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-08-06 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0118_auto_20180805_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='eliminado',
            field=models.BooleanField(default=0),
        ),
    ]
