# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-08-11 22:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0121_auto_20180810_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocodigo',
            name='cliente_compartido',
            field=models.ForeignKey(blank=True, db_column='cliente_compartido', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cliente_compartido', to='app.Cliente'),
        ),
        migrations.AlterField(
            model_name='traficosms',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 11, 17, 1, 52, 776351), null=True),
        ),
    ]
