# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-08-12 15:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0123_auto_20180811_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campania',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=1000, null=True)),
                ('fecha', models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 12, 10, 30, 12, 696479), null=True)),
                ('filtro', models.CharField(blank=True, max_length=1000, null=True)),
                ('estado', models.ForeignKey(blank=True, db_column='estado_compartir', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Estadocompartir')),
            ],
        ),
        migrations.CreateModel(
            name='EnvioMasivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=1000, null=True)),
                ('apellido', models.CharField(blank=True, max_length=1000, null=True)),
                ('edad', models.CharField(blank=True, max_length=1000, null=True)),
                ('telefono', models.CharField(blank=True, max_length=1000, null=True)),
                ('email', models.CharField(blank=True, max_length=1000, null=True)),
                ('direccion', models.CharField(blank=True, max_length=1000, null=True)),
                ('distrito', models.CharField(blank=True, max_length=1000, null=True)),
                ('fijo', models.CharField(blank=True, max_length=1000, null=True)),
                ('sexo', models.CharField(blank=True, max_length=1000, null=True)),
                ('trabajo', models.CharField(blank=True, max_length=1000, null=True)),
                ('dni', models.CharField(blank=True, max_length=1000, null=True)),
                ('fecha_nacimiento', models.CharField(blank=True, max_length=1000, null=True)),
                ('origen', models.CharField(blank=True, max_length=1000, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('campania', models.ForeignKey(blank=True, db_column='campania', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Campania')),
            ],
            options={
                'verbose_name': 'Envio Masivo',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='promocodigo',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 12, 10, 30, 12, 694063), null=True),
        ),
        migrations.AlterField(
            model_name='traficosms',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 12, 10, 30, 12, 705094), null=True),
        ),
    ]
