# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-08-12 15:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0124_auto_20180812_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='campania',
            name='descripcion',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='campania',
            name='email',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='campania',
            name='notificacion',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='campania',
            name='sms',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='campania',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 12, 10, 41, 48, 176446), null=True),
        ),
        migrations.AlterField(
            model_name='promocodigo',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 12, 10, 41, 48, 174223), null=True),
        ),
        migrations.AlterField(
            model_name='traficosms',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 12, 10, 41, 48, 185486), null=True),
        ),
    ]
