# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-08-12 15:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0125_auto_20180812_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='campania',
            name='activo',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='campania',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 12, 10, 42, 44, 671), null=True),
        ),
        migrations.AlterField(
            model_name='promocodigo',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 12, 10, 42, 43, 998539), null=True),
        ),
        migrations.AlterField(
            model_name='traficosms',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 12, 10, 42, 44, 9982), null=True),
        ),
    ]
