# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-08-13 17:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0126_auto_20180812_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='traficosms',
            name='codigo',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='campania',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 13, 12, 23, 36, 621707), null=True),
        ),
        migrations.AlterField(
            model_name='campania',
            name='filtro',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='promocodigo',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 13, 12, 23, 36, 617199), null=True),
        ),
        migrations.AlterField(
            model_name='traficosms',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 13, 12, 23, 36, 637472), null=True),
        ),
    ]
