# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-08-16 04:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0127_auto_20180813_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='socia',
            name='descripcion_socia',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='socia',
            name='descripcion_titulo',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='campania',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 15, 23, 6, 23, 37881), null=True),
        ),
        migrations.AlterField(
            model_name='promocodigo',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 15, 23, 6, 23, 35616), null=True),
        ),
        migrations.AlterField(
            model_name='traficosms',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 15, 23, 6, 23, 46856), null=True),
        ),
    ]
