# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-08-16 04:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0128_auto_20180815_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campania',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 15, 23, 7, 19, 846716), null=True),
        ),
        migrations.AlterField(
            model_name='promocodigo',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 15, 23, 7, 19, 844443), null=True),
        ),
        migrations.AlterField(
            model_name='socia',
            name='descripcion_socia',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='traficosms',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 15, 23, 7, 19, 855956), null=True),
        ),
    ]
