# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-08-18 13:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0129_auto_20180815_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciopedido',
            name='estrella',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campania',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 18, 8, 2, 8, 760942), null=True),
        ),
        migrations.AlterField(
            model_name='promocodigo',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 18, 8, 2, 8, 758716), null=True),
        ),
        migrations.AlterField(
            model_name='traficosms',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 18, 8, 2, 8, 770192), null=True),
        ),
    ]
