# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-08-25 21:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0131_auto_20180825_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='photo_home',
            field=models.FileField(blank=True, null=True, upload_to='static'),
        ),
        migrations.AlterField(
            model_name='campania',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 25, 16, 38, 45, 957635), null=True),
        ),
        migrations.AlterField(
            model_name='promocodigo',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 25, 16, 38, 45, 954756), null=True),
        ),
        migrations.AlterField(
            model_name='traficosms',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 25, 16, 38, 45, 970709), null=True),
        ),
    ]
