# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-08-26 02:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0132_auto_20180825_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='socia',
            name='estrellas',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='campania',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 25, 21, 47, 18, 686702), null=True),
        ),
        migrations.AlterField(
            model_name='promocodigo',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 25, 21, 47, 18, 684303), null=True),
        ),
        migrations.AlterField(
            model_name='traficosms',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 25, 21, 47, 18, 700654), null=True),
        ),
    ]
