# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-08-26 03:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0133_auto_20180825_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sociacomentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(blank=True, max_length=1000, null=True)),
                ('fecha', models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 25, 22, 54, 8, 736854))),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Cliente')),
                ('socia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Socia')),
            ],
            options={
                'verbose_name': 'Socia/ Comentario',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='campania',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 25, 22, 54, 8, 731126), null=True),
        ),
        migrations.AlterField(
            model_name='promocodigo',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 25, 22, 54, 8, 728990), null=True),
        ),
        migrations.AlterField(
            model_name='traficosms',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 25, 22, 54, 8, 740337), null=True),
        ),
    ]
