# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-09-02 14:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0136_auto_20180831_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='socia',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='campania',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 2, 9, 42, 16, 642483), null=True),
        ),
        migrations.AlterField(
            model_name='personalizar',
            name='logo',
            field=models.FileField(blank=True, help_text='Subir un logo 500 x 200', null=True, upload_to='static'),
        ),
        migrations.AlterField(
            model_name='promocodigo',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 2, 9, 42, 16, 640490), null=True),
        ),
        migrations.AlterField(
            model_name='sociacomentario',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 2, 9, 42, 16, 648192)),
        ),
        migrations.AlterField(
            model_name='traficosms',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 2, 9, 42, 16, 651530), null=True),
        ),
    ]
