# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-09-02 15:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0138_auto_20180902_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociasubcategoria',
            name='costo',
            field=models.IntegerField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='campania',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 2, 10, 33, 34, 449655), null=True),
        ),
        migrations.AlterField(
            model_name='promocodigo',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 2, 10, 33, 34, 447710), null=True),
        ),
        migrations.AlterField(
            model_name='sociacomentario',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 2, 10, 33, 34, 455854)),
        ),
        migrations.AlterField(
            model_name='traficosms',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 2, 10, 33, 34, 459128), null=True),
        ),
    ]
