# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-09-04 23:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0141_auto_20180904_1824'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientesocias',
            options={'managed': True, 'verbose_name': 'Clientesocias'},
        ),
        migrations.AlterField(
            model_name='campania',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 4, 18, 47, 9, 513711), null=True),
        ),
        migrations.AlterField(
            model_name='promocodigo',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 4, 18, 47, 9, 511625), null=True),
        ),
        migrations.AlterField(
            model_name='sociacomentario',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 4, 18, 47, 9, 535205)),
        ),
        migrations.AlterField(
            model_name='traficosms',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 4, 18, 47, 9, 554676), null=True),
        ),
    ]
