# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-09-04 23:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0142_auto_20180904_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historiaclientesocias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(blank=True, max_length=1000, null=True)),
                ('fecha', models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 4, 18, 54, 29, 131231), null=True)),
                ('alerta', models.DateTimeField(blank=True, null=True)),
                ('clientesocia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Clientesocias')),
            ],
            options={
                'verbose_name': 'Historiaclientesocias',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='campania',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 4, 18, 54, 29, 103982), null=True),
        ),
        migrations.AlterField(
            model_name='promocodigo',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 4, 18, 54, 29, 101398), null=True),
        ),
        migrations.AlterField(
            model_name='sociacomentario',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 4, 18, 54, 29, 112602)),
        ),
        migrations.AlterField(
            model_name='traficosms',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 4, 18, 54, 29, 116474), null=True),
        ),
    ]
