# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-09-16 16:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0144_auto_20180909_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sociacategoriaphoto',
            name='sociacategoria',
        ),
        migrations.AddField(
            model_name='sociacategoriaphoto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Categoria'),
        ),
        migrations.AddField(
            model_name='sociacategoriaphoto',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 16, 11, 49, 26, 998855)),
        ),
        migrations.AddField(
            model_name='sociacategoriaphoto',
            name='socia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Socia'),
        ),
        migrations.AlterField(
            model_name='campania',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 16, 11, 49, 26, 986433), null=True),
        ),
        migrations.AlterField(
            model_name='historiaclientesocias',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 16, 11, 49, 27, 33816), null=True),
        ),
        migrations.AlterField(
            model_name='promocodigo',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 16, 11, 49, 26, 983055), null=True),
        ),
        migrations.AlterField(
            model_name='sociacomentario',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 16, 11, 49, 27, 346)),
        ),
        migrations.AlterField(
            model_name='traficosms',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 16, 11, 49, 27, 6459), null=True),
        ),
    ]
